[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_DISABLE_PRERENDER_AUTH = "true"

# Skip prerendering of auth pages
[[plugins.inputs.skipPrerender]]
  patterns = ["/login", "/register", "/profile"]
