-- Property history (Option B): snapshot + diff events
-- Captured only when a user views a property page (SSR).

create table if not exists public.property_view_snapshots (
  id bigint generated by default as identity primary key,
  listing_key text not null,
  captured_at timestamptz not null default now(),
  snapshot_hash text not null,
  snapshot jsonb not null,

  -- extracted fields for querying/diffing
  standard_status text,
  list_price numeric,
  close_price numeric,
  close_date date,
  major_change_type text,
  major_change_timestamp timestamptz,
  status_change_timestamp timestamptz,
  price_change_timestamp timestamptz,
  modification_timestamp timestamptz,
  on_market_date date,
  off_market_date date
);

create unique index if not exists property_view_snapshots_listing_hash_uidx
  on public.property_view_snapshots (listing_key, snapshot_hash);

create index if not exists property_view_snapshots_listing_captured_idx
  on public.property_view_snapshots (listing_key, captured_at desc);

create table if not exists public.property_history_events (
  id bigint generated by default as identity primary key,
  listing_key text not null,
  event_at timestamptz not null,
  event_type text not null,
  event_label text,
  old_value jsonb,
  new_value jsonb,
  source text not null default 'snapshot_diff',
  created_at timestamptz not null default now()
);

create index if not exists property_history_events_listing_event_idx
  on public.property_history_events (listing_key, event_at desc);

alter table public.property_view_snapshots enable row level security;
alter table public.property_history_events enable row level security;

-- No RLS policies added intentionally.
-- Server uses SUPABASE_SERVICE_KEY/SUPABASE_ADMIN_KEY (service role) which bypasses RLS.
